# Change these first
owner: SOIV-Studio # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  # 폴더 구조로 정리
  - name: "🌐 Main Website"
    url: https://soiv-studio.xyz
    
  - name: "📊 Dashboard"
    url: https://dashboard.soiv-studio.xyz

  - name: "🤖 Discord Bot"
    url: https://bot-status.soiv-studio.xyz/health
    method: GET  # 요청 방식
    
  # Backend Services 폴더
  - name: "🔧 Backend API - Health Check"
    url: https://bot-api.soiv-studio.xyz/health
    expectedStatusCodes:
      - 200
    
  - name: "🔧 Backend API - Auth Status"
    url: https://bot-api.soiv-studio.xyz/api/auth-status
    expectedStatusCodes:
      - 200
      - 401  # 인증 안된 상태도 정상으로 처리
    
  - name: "🔧 Backend API - DB Status"
    url: https://bot-api.soiv-studio.xyz/api/db-status
    expectedStatusCodes:
      - 200
    
  # Discord OAuth 폴더  
  - name: "🎮 Discord OAuth Service"
    url: https://bot-api.soiv-studio.xyz/auth/discord
    method: GET
    expectedStatusCodes:
      - 302  # 리다이렉트는 정상
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.soiv-studio.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SOIV Studio status page
  introTitle: "Service status page"
  introMessage: Check the current status and past outage history of all services
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Dashboard
      href: https://dashboard.soiv-studio.xyz

  # 커스텀 CSS 적용
  theme: custom
  customCSS: assets/custom.css
  
  # 파비콘
  faviconSvg: https://example.com/favicon.svg
  favicon: https://example.com/favicon.ico
  
  # 메타 정보
  metaTags:
    - name: "description"
      content: "실시간 서비스 상태 모니터링 페이지"
    - name: "author"
      content: "SOIV Studio"
    - property: "og:title"
      content: "서비스 상태 페이지"
    - property: "og:description"
      content: "모든 서비스의 실시간 상태를 확인하세요"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration